ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from ecommerce.views import homepage

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", homepage, name="homepage"),  # http://localhost:8000
    path("products/", include("products.urls")),  # http://localhost:8000/products
    path("users/", include("users.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/products/urls.py
from django.urls import path
from products.views import get_all_products, get_product

app_name = "products"


urlpatterns = [
    path("", get_all_products, name="products_list"),  # http://localhost:8000/products
    path("<int:product_id>/", get_product, name="product_details"),  # http://localhost:8000/products/<product-id>
]

ecommerce/users/urls.py
from django.urls import path
from users.views import register

app_name = "users"

urlpatterns = [
    path("register/", register, name="register")
]

ecommerce/products/models.py
from django.db import models
from django.contrib import admin
from django.templatetags.static import static


class Category(models.Model):
    class Meta:
        verbose_name_plural = "categories"

    name = models.CharField(max_length=255, unique=True)
    parent = models.ForeignKey("Category", null=True, default=None, on_delete=models.CASCADE)
    type = models.CharField(
        max_length=20,
        choices=(("department", "Department"), ("category", "Category"), ("subcategory", "Subcategory")),
        default="department"
    )


class Product(models.Model):
    name = models.CharField(max_length=255)
    image = models.ImageField(upload_to="products/")
    price = models.DecimalField(max_digits=6, decimal_places=2)  # 9999.99
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, default=None)

    def parent_subcategory(self):
        return self.category

    def parent_category(self):
        # return self.category.parent
        return self.parent_subcategory().parent

    @property
    @admin.display(description="image")
    def image_src(self):
        if self.image:
            return self.image.url

        return static("images/default-product-image.png")

    def parent_department(self):
        # return self.category.parent.parent
        return self.parent_category().parent

    def __str__(self):
        return self.name

ecommerce/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.hashers import make_password


class UserManager(BaseUserManager):
    def _create_user(self, email, first_name, last_name, password, **extra_fields):
        """
        Create and save a user with the given username, email, and password.
        """
        if not email:
            raise ValueError("The given email must be set")
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        user = self.model(email=email, first_name=first_name, last_name=last_name, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, first_name, last_name, password, **extra_fields)

    def create_superuser(self, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, first_name, last_name, password, **extra_fields)


class AuthUser(AbstractUser):
    username = None
    email = models.EmailField(_("email address"), unique=True, null=False, blank=False)
    first_name = models.CharField(_("first name"), max_length=150, blank=False, null=False)
    last_name = models.CharField(_("last name"), max_length=150, blank=False, null=False)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = ["first_name", "last_name"]

    objects = UserManager()

ecommerce/products/forms.py
from django import forms
from products.models import Product


class ProductsByPrice(forms.Form):
    min_price = forms.DecimalField(required=False, label="Min", min_value=0.00)
    max_price = forms.DecimalField(required=False, label="Max", min_value=0.00)

    def clean(self):
        min_price = self.cleaned_data.get("min_price", 0)
        max_price = self.cleaned_data.get("max_price", 0)

        if min_price == 300 and max_price == 200:
            raise forms.ValidationError({
                "min_price": "Min price hardcoded value invalid!",
                "max_price": "Max price hardcoded value invalid!",
            })

        return {
            "min_price": min_price,
            "max_price": max_price,
        }

    def clean_max_price(self):
        min_price = self.cleaned_data.get("min_price", 0)
        max_price = self.cleaned_data.get("max_price", 0)

        is_min_price_set = min_price is not None
        is_max_price_set = max_price is not None

        if is_min_price_set and is_max_price_set and max_price < min_price:
            raise forms.ValidationError("max_price cannot be lower than min_price!")

        return max_price

    def get_filtered_products(self):
        products = Product.objects

        min_price = self.cleaned_data.get("min_price")
        max_price = self.cleaned_data.get("max_price")
        print('\n' * 2)
        print('max_price', max_price)
        print('\n' * 2)

        if min_price:
            products = products.filter(price__gte=min_price)

        if max_price:
            products = products.filter(price__lte=max_price)

        return products.all()

ecommerce/users/forms.py
from django.contrib.auth.forms import BaseUserCreationForm
from users.models import AuthUser


class UserCreationForm(BaseUserCreationForm):
    class Meta:
        model = AuthUser
        fields = ("email", "first_name", "last_name")

ecommerce/ecommerce/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, "homepage.html")

ecommerce/products/views.py
from django.shortcuts import render, Http404, get_object_or_404
from products.models import Product
from products.forms import ProductsByPrice


# def get_all_products(request):
#     min_price = request.GET.get("min")
#     max_price = request.GET.get("max")
#
#     # products = Product.objects.all()
#     # products = Product.objects.filter(price=2099.99).all()
#     # products = Product.objects.filter(price__gte=min_price, price__lte=max_price).all()
#     products = Product.objects
#     if min_price:
#         products = products.filter(price__gte=min_price)
#     if max_price:
#         products = products.filter(price__lte=max_price)
#
#     return render(request, "products_list.html", {
#         "products": products.all()
#     })
def get_all_products(request):
    form = ProductsByPrice(request.GET)
    if form.is_valid():
        products = form.get_filtered_products()
    else:
        products = []

    return render(request, "products_list.html", {
        "products": products,
        "form": form,
    })


def get_product(request, product_id):
    # try:
    #     product = Product.objects.get(id=product_id)
    # except Product.DoesNotExist:
    #     raise Http404(f"Product with ID = {product_id} does not exist.")

    product = get_object_or_404(Product, pk=product_id)
    # product = get_object_or_404(Product, id=product_id)

    return render(request, "product_details.html", {
        "product": product
    })

ecommerce/users/views.py
from django.shortcuts import render, redirect
# from django.contrib.auth.forms import UserCreationForm
from users.forms import UserCreationForm


def register(request):
    if request.method == "GET":
        form = UserCreationForm()
    else:
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect("/")

    return render(request, "users/register.html", {
        "form": form
    })

ecommerce/products/templates/product_details.html
{#<html>#}
{#    <head>#}
{#        <title>Product details page</title>#}
{#    </head>#}
{#    <body>#}
{#        <h1>Product details page</h1>#}
{#        <p>Name: {{ product.name }}</p>#}
{#        <p>Price: {{ product.price }} RON</p>#}
{#    </body>#}
{#</html>#}

{% extends "base.html" %}

{% block title %}
    <title>{{ product.name }}</title>
{% endblock %}

{% block content %}
    <h1>Product details page</h1>
    {% comment %}<p>Department: {{ product.category.parent.parent.name }}</p>
    <p>Category: {{ product.category.parent.name }}</p>
    <p>Subcategory: {{ product.category.name }}</p>{% endcomment %}
    <p>Department: {{ product.parent_department.name }}</p>
    <p>Category: {{ product.parent_category.name }}</p>
    <p>Subcategory: {{ product.parent_subcategory.name }}</p>
    <p>Name: {{ product.name }}</p>
    <p>Price: {{ product.price }} RON</p>
    <img src="{{ product.image_src }}" width="200" />
{% endblock %}

ecommerce/products/templates/products_list.html
{#<html>#}
{#    <head>#}
{#        <title>Products page</title>#}
{#        <style>#}
{#            .products-list li {#}
{#                display: flex;#}
{#                align-items: center;#}
{#            }#}
{#            .products-list li a {#}
{#                margin-left: 20px;#}
{#            }#}
{#        </style>#}
{#    </head>#}
{#    <body>#}
{#        {% include "navigation.html" %}#}
{#        <h1>Products page</h1>#}
{#        <ul class="products-list">#}
{#            {% for product in products %}#}
{#                <li>#}
{#                    <h2>{{ product.name }} ({{ product.price }} RON)</h2>#}
{#                    <a>View details</a>#}
{#                </li>#}
{#            {% endfor %}#}
{#        </ul>#}
{#    </body>#}
{#</html>#}

{% extends "base.html" %}
{% load static %}

{% block title %}
    <title>Products page</title>
{% endblock %}

{% block style %}
    <style>
        .products-list li {
            display: flex;
            align-items: center;
        }
        .products-list li a {
            margin-left: 20px;
        }
    </style>
{% endblock %}

{% block content %}
    <h1>Products page ({{ products | length }})</h1>
    {% comment %}<form method="get" action="{% url 'products:products_list' %}">
        <input type="number" name="min" min="0" step="100" />
        <input type="number" name="max" min="0" step="100" />
        <input type="submit" value="Filter" />
    </form>{% endcomment %}
    <form method="get" action="{% url 'products:products_list' %}" novalidate>
        {{ form.as_p }}
        <input type="submit" value="Filter" />
    </form>
    <ul class="products-list">
        {% for product in products %}
            <li>
                <h4>{{ product.name | truncatechars:50 }} ({{ product.price }} RON)</h4>
                <img src="{{ product.image_src }}" width="50" />
                <a href="{% url 'products:product_details' product.id %}">View details</a>
            </li>
        {% endfor %}
    </ul>
{% endblock %}

ecommerce/templates/base.html
{% load static %}
<html>
    <head>
        {% block title %}
        {% endblock %}
        {% block style %}
        {% endblock %}
        <link rel="stylesheet" href="{% static 'styles/main.css' %}" />
        <script src="{% static 'js/sample.js' %}"></script>
    </head>
    <body>
        {% include "navigation.html" %}
        {% block content %}
        {% endblock %}
    </body>
</html>

ecommerce/templates/homepage.html
{#<html>#}
{#    <head>#}
{#        <title>#}
{#            First Django Project#}
{#        </title>#}
{#    </head>#}
{#    <body>#}
{#        {% include "navigation.html" %}#}
{#        <h1>This is my first Django project</h1>#}
{#    </body>#}
{#</html>#}

{% extends "base.html" %}

{% block title %}
    <title>First Django Project</title>
{% endblock %}

{% block content %}
    <h1>This is my first Django project</h1>
{% endblock %}

ecommerce/templates/navigation.html
{% load static %}
<nav>
    <div>
        <img src="{% static 'images/logo.svg' %}" height="60" />
    </div>
    <ul>
        <li>
            <a href="{% url 'homepage' %}">Home</a>
        </li>
        <li>
            <a href="{% url 'products:products_list' %}">Products</a>
        </li>
    </ul>
</nav>

ecommerce/users/templates/users/register.html
<html>
    <body>
        <form method="post" action="{% url 'users:register' %}">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Register" />
        </form>
    </body>
</html>